- name: Set version specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Manage cockpit packages using platform specific package manager if applicable
  include_tasks: "{{ item }}"
  with_first_found:
    - "setup-{{ ansible_pkg_mgr }}.yml"
    - "setup-default.yml"

- name: Ensure Cockpit Web Console is started/stopped based on cockpit_started variable
  service:
    name: "{{ __cockpit_daemon }}"
    state: "{{ 'started' if cockpit_started | bool else 'stopped' }}"

- name: Ensure Cockpit Web Console is enabled/disabled on boot based on cockpit_enabled variable
  service:
    name: "{{ __cockpit_daemon }}"
    enabled: "{{ cockpit_enabled | bool }}"
